### GET request to example server
GET http://api.odcloud.kr/api/15003087/v1/uddi:89fab983-66d8-40ad-901a-d535f8699d29?page=1&perPage=2000&serviceKey=I%2BLq678BJU%2B547TEKBXQDCAIGMBKm3RIzTDUSUNuC8VyNSc30c%2FcbH8fMY40AutRcx6IKR1McOUXc1xb9kjXRA%3D%3D
